frontend:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - frontend/**/*
backend:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - backend/**/*
feature:
- any:
  - head-branch:
    - ^feature/
