name: Callable Workflow
run_name: Called Workflow

on:
  workflow_call:
    inputs:
      x:
        type: number
        default: 8
      y:
        type: number
        default: 17
    outputs:
      sum:
        type: number
        description: The sum of inputs
        value: ${{ jobs.calculate.outputs.sum }}
      difference:
        type: number
        description: The difference of inputs
        value: ${{ jobs.calculate.outputs.difference }}

jobs:
  calculate:
    runs-on: ubuntu-latest
    outputs:
      sum: ${{ steps.sum.outputs }}
      difference: ${{ steps.difference.outputs }}
    steps:
    - name: Show env GITHUB_OUTPUT
      run: |
        echo $GITHUB_OUTPUT
        ls -al $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
    - name: Print inputs
      run: |
        echo x: ${{ inputs.x }}  y: ${{ inputs.y }}
    - name: Evaluate sum
      id: sum
      run: |
        sum=expr ${{ inputs.x }} + ${{ inputs.y }}
        echo "sum=$sum" >> $GITHUB_OUTPUT
    - name: Evaluate difference
      id: difference
      run: |
        difference=$(expr ${{ inputs.x }} - ${{ inputs.y }})
        echo "difference=$difference" >> $GITHUB_OUTPUT
    - name: Show content of GITHUB_OUTPUT again
      run: |
        echo $GITHUB_OUTPUT
        ls -al $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
