name: Workflow that calls

on:
  workflow_dispatch:

jobs:
  call: # notice how we use another workflow at the job level, not step level
    uses: .github/workflows/callable-workflow.yml@latest
    with:
      x: 6
      y: 19
  result:
    runs-on: ubuntu-latest
    needs: call
    steps:
    - name: Show output of called workflow
      run: |
        echo ${{ needs.call.outputs.sum }}
        echo ${{ needs.call.outputs.differnce }}
