name: Create Package

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: 1.0.0
      registry:
        type: string
        default: ghcr.io

env:
  image_tag: "${{ inputs.registry }}/${{ github.repository.lowercase }}:${{ inputs.version }}"
  image_source: ${{ github.server_url }}/${{ github.repository.lowercase }}

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - name: build image
      run: |
        docker build
          --tag $image_tag \
          --file app/Dockerfile \
          --label version=${{ inputs.version }}
          --label "org.opencontainers.image.source=$image_source \
          --label "org.opencontainers.image.description='Simple container'" \
          --label "org.opencontainers.image.licenses=MIT" \
          ./app
    - name: login registry
      run: |
        docker login ${{ inputs.registry }} -u GITHUB --password-stdin $GITHUB_TOKEN
    - name: upload image
      run: |
        docker push $image_tag
