name: Create Package

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: 1.0.0
      registry:
        type: string
        default: ghcr.io

jobs:
  repository:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.format.outputs.REPO_NAME }}
    steps:
    - name: format repository name
      id: format
      run: |
        name=${{ github.repository }}
        lower=${name,,}
        echo $lower
        echo "REPO_NAME=$lower" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - uses: actions/checkout@v4
    - name: build
      id: build
      run: |
        cd app
        npm install --omit=dev
        npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist
        retention-days: 3

  publish:
    needs:
    - repository
    - build
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ inputs.registry }}/${{ needs.repository.outputs.name }}:${{ inputs.version }}
      IMAGE_SRC: ${{ github.server_url }}/${{ needs.repository.outputs.name }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: dist
    - name: show image info
      run: |
        echo $IMAGE_TAG
        echo $IMAGE_SRC
        ls -al dist
    - name: build image
      run: |
        cd app
        docker build \
          --tag $IMAGE_TAG \
          --file Dockerfile \
          --label version=${{ inputs.version }} \
          --label "org.opencontainers.image.source=$IMAGE_SRC" \
          --label "org.opencontainers.image.description='simple container'" \
          --label "org.opencontainers.image.licenses=MIT" \
          .
    - name: login registry
      run: |
        docker login ${{ inputs.registry }} -u GITHUB --password-stdin $GITHUB_TOKEN
    - name: upload image
      run: |
        docker push $image_tag
