name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        default: 1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh release create v${{ inputs.tag }} --generate-notes
# this will also create the tag in git, which you can later fetch using git fetch --tags
