name: Create Package

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        default: 1.0.0

env:
  image_name: ${{ github.repository.lowercase }}
  image_source: ${{ github.server_url/github.repository.lowercase }}

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - name: build image
      run: |
        docker build
          --tag ghcr.io/$image_name \
          --file app/Dockerfile \
          --label version=${{ inputs.tag }}
          --label "org.opencontainers.image.source=$image_source \
          --label "org.opencontainers.image.description='Simple container'" \
          --label "org.opencontainers.image.licenses=MIT" \
          ./app
    - name: login registry
      run: |
        docker login ghcr.io -u GITHUB --password-stdin $GITHUB_TOKEN
    - name: upload image
      run: |
        docker push ghcr.io/$image_name:${{ inputs.tag }}
