name: Create Package

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: 1.0.0
      registry:
        type: string
        default: ghcr.io

jobs:
  repository:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.format.outputs.REPO_NAME }}
    steps:
    - name: format repository name
      id: format
      run: |
        name=${{ github.repository }}
        lower=${name,,}
        echo $lower
        echo "REPO_NAME=$lower" >> $GITHUB_OUTPUT
  pack:
    needs:
    - repository
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ inputs.registry }}/${{ needs.repository.outputs.name }}:${{ inputs.version }}
      IMAGE_SRC: ${{ github.server_url }}/${{ needs.repository.outputs.name }}
    steps:
    - name: checkout repository
      runs: actions/checkout@v4
    - name: show image info
      run: |
        echo $IMAGE_TAG
        echo $IMAGE_SRC
    - name: build image
      run: |
        docker build \
          --tag $IMAGE_TAG \
          --file app/Dockerfile \
          --label version=${{ inputs.version }} \
          --label "org.opencontainers.image.source=$IMAGE_SRC" \
          --label "org.opencontainers.image.description='simple container'" \
          --label "org.opencontainers.image.licenses=MIT" \
          ./app
    - name: login registry
      run: |
        docker login ${{ inputs.registry }} -u GITHUB --password-stdin $GITHUB_TOKEN
    - name: upload image
      run: |
        docker push $image_tag
