name: Detect Change in File

on:
  workflow_dispatch:

jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: "hash: ${{ hashFiles('app/src/**/*') }}"
    - name: download cache
      id: cache
      uses: actions/cache@v4
      with:
        path: .
        key: src-${{ hashFiles('app/src/**/*') }}
    - name: "cache-hit: ${{ steps.cache.outputs.cache-hit != 'true' }}"
