name: Detect Change in File

on:
  workflow_dispatch:

jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: print hashes
      run: |
        echo ${{ hashFiles('app/src/**/*') }}
    - name: download cache
      id: cache
      uses: actions/cache@v4
      with:
        path: .
        key: src-${{ hashFiles('app/src/**/*') }}
    - name: check cache hit
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: |
        echo hash is different
        echo app/src changed!
