name: Label PR

on:
  pull_request_target:

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Label branch
      id: labeler
      uses: actions/labeler@v5
    - name: Show label changes
      run: |
        echo new-labels: ${{ steps.labeler.outputs.new-labels }}
        echo all-labels: ${{ steps.labeler.outputs.all-labels }}
