name: Multiple Jobs in one workflow

on:
  workflow_dispatch:


jobs:
  # by default, jobs are run in parallel
  job_A:
    runs-on: ubuntu-latest
    steps:
    - name: Print Job Name
      run: echo now running ${{ github.job }}
  job_B:
    runs-on: ubuntu-latest
    steps:
    - name: Print Job Name
      run: echo now running ${{ github.job }}
  job_C:
    runs-on: ubuntu-latest
    steps:
    - name: Print Job Name
      run: echo now running ${{ github.job }}

  # specify dependency between jobs
  job_D:
    runs-on: ubuntu-latest
    needs: job_F
    steps:
    - name: Print Job Name
      run: echo now running ${{ github.job }}
  job_E:
    runs-on: ubuntu-latest
    needs:
    - job_F
    - job_G
    steps:
    - name: Print Job Name
      run: echo now running ${{ github.job }}
  job_F:
    runs-on: ubuntu-latest
    steps:
    - name: Print Job Name
      run: echo now running ${{ github.job }}
  job_G:
    runs-on: ubuntu-latest
    steps:
    - name: Print Job Name
      run: echo now running ${{ github.job }}
