name: Print env and related info

on:
  workflow_dispatch:
    inputs:
      dummy_var:
        default: placeholder-value

jobs:
  print_env:
    runs-on: ubuntu-latest
    steps:
    - name: Print env variables
      run: printenv
    - name: Print inputs
      run: echo ${{ inputs }}
    - name: Print github
      run: echo ${{ github }}
    - name: List binaries (commands you can use)
      run: ls -al /bin
    - name: Print current directory
      run: pwd
    - name: Print kernel
      run: uname -a
