name: Push Image to AWS ECR

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        default: 1.0.0

jobs:
# in real project, you want to split the steps into compile, build, push
  push:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: login aws ecr
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} |
          docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}
    - name: compile app
      run: |
        cd app
        npm install --omit=dev
        npm run build
    - name: build image
      run: |
        docker build \
          --file ./Dockerfile \
          --tag ${{ secrets.ECR_REPOSITORY }}:${{ inputs.tag }} \
          .
    - name: list images
      run: |
        docker image ls
    - name: push image
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:${{ inputs.tag }}
