name: Using Cache (Artifact)

on:
  workflow_dispatch:
    inputs:
      filename:
        type: string
        default: github-workflow.log

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Create log file
      run: |
        cat <<-EOF > ${{ inputs.filename }}
          This is a log generated in github actions.
          It will be stored in cache.
        EOF
        echo $(date) >> ${{ inputs.filename }}
    - name: Show created file
      run: |
        ls ${{ inputs.filename }}
        cat ${{ inputs.filename }}
    - name: Upload
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.filename }}
        path: ./${{ inputs.filename }}
        retention-days: 1
    - name: Show artifact info
      run: |
        echo ${{ steps.upload.outputs.artifact-id }}
        echo ${{ steps.upload.outputs.artifact-url }}
        echo ${{ steps.upload.outputs.artifact-digest }}
  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - name: Download
      uses: actions/download-artifact@v4
      with: ${{ inputs.filename }}
    - name: Print file
      run: cat ${{ inputs.filename }}
    - name: Show cache info
      run: ls -alh ${{ inputs.filename }} 
