name: Using Env Vars

on:
  workflow_dispatch:

env:  # workflow env
  season: summer

jobs:
  print_env:
    runs-on: ubuntu-latest
    env:
      count: 7
    steps:
    - name: echo env vars
      env: # step env
        tea: green
      run: |
        echo workflow env: $season
        echo job env: $count
        echo step env: $tea
    - name: echo repo vars
      env:
        REPO_ENV_VAR: ${{ vars.REPO_ENV_VAR }}
        REPO_ENV_SECRET: ${{ vars.REPO_ENV_SECRET }} # do not print this in real project
      run: |
        echo $REPO_ENV_VAR
        echo $REPO_ENV_SECRET
        env
